name: distrowatchapp
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  xml: ^3.4.1
  flutter_redux: ^0.5.0
  intl: ^0.15.8
  url_launcher: ^5.0.2
  path_provider: ^0.5.0+1
  shared_preferences: ^0.5.2
  html: ^0.14.0+2
  test: ^1.6.2
  rxdart: ^0.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/preloaded_data/theaters.xml
  - assets/images/1x1_transparent.png
  - assets/images/powered_by_tmdb.png